USE shruthi;
USE jun_19th;
CREATE TABLE Bank(bank_id int primary key,bank_name varchar(20),address varchar(20),account_type varchar(10),loan_amt int);
CREATE DATABASE Company;
drop database company;
SHOW databases;
CREATE TABLE Company(company_id int primary key,company_name varchar(20),address varchar(20),started_year int,TOtalemployees int);
drop table employee;
CREATE TABLE Orders(order_id int primary key,ordre_type varchar(10),total_amt int);
CREATE TABLE Revanue(year int,profit int);
CREATE TABLE Customers(cust_id int primary key,cust_Fname varchar(10),cust_Lname varchar(10),cust_address varchar(10));
select *from company;
CREATE DATABASE sep1;
CREATE TABLE Artist(artist_id int primary key,artist_name varchar(10),artist_type varchar(10),exp int,age int,address varchar(18));
CREATE TABLE Jacket(brand_id int,size varchar(10),brand varchar(10),cost int,type varchar(18));
CREATE TABLE Patient(id int primary key,name varchar(10),address varchar(10),admit_date date);
CREATE TABLE Politician(name varchar(10),address varchar(10),age int,party_name varchar(10));
CREATE TABLE Grocery(product_id int primary key,brand varchar(10),price int,type varchar(10),quantity varchar(10));
CREATE TABLE HistoricalPlaces(name varchar(10),age int,architectural_style varchar(20),place varchar(10));
CREATE TABLE Pilot(id int primary key,Fname varchar(10),Lname varchar(10),exp int,address varchar(10));
CREATE TABLE Medicine(med_id int primary key, manf_date date,exp_date date,cost int);
desc artist;
insert into artist values(101,'sushsnt','actor',10,35,'mumbai');
insert into artist values(102,'sanjith_hegde','singer',5,24,'banglore');
insert into artist values(103,'shreya','singer',15,35,'mumbai');
insert into artist values(104,'chandan','singer',10,35,'banglore');
insert into artist values(105,'darshan','actor',24,45,'banglore');
insert into artist values(106,'sudeep','actor',20,52,'banglore');
insert into artist values(107,'radhika','actress',10,35,'banglore');
insert into artist values(108,'katrina','actress',22,38,'mumbai');
insert into artist values(109,'shahid','actor',15,35,'andhra');
insert into artist values(110,'arjun','singer',12,35,'banglore');
insert into artist values(111,'rakulpreet','actress',12,35,'telngan');
desc jacket;
select *from artist;
insert into Jacket values(01,'small','zaara',5000,'classic');
insert into Jacket values(02,'medium','',4000,'classic');
insert into Jacket values(03,'large','felima',3000,'classic');
insert into Jacket values(04,'xl','puma',7000,'classic');
insert into Jacket values(05,'xs','tsla',6000,'classic');
insert into Jacket values(06,'small','tapata',4000,'classic');
insert into Jacket values(07,'medium','zaara',8000,'classic');
insert into Jacket values(08,'large','synpos',6000,'classic');
insert into Jacket values(09,'small','zaara',5000,'classic');
insert into Jacket values(10,'medium','zaara',2000,'classic');
insert into Jacket values(11,'small','armani',6000,'classic');
select *from Politician;
desc pilot;
insert into patient values(9,'anil','manipal',08/05/22);
insert into patient values(11,'arya','udupi',08/11/22);
insert into patient values(12,'anvit','kundapur',08/10/23);
insert into patient values(13,'vinil','telangan',08/10/21);
insert into patient values(14,'vijay','kumta',08/12/22);
insert into patient values(15,'vishwesh','manipal',16/12/20);
insert into patient values(16,'vignesh','manki',08/01/22);
insert into patient values(17,'arha','uk',08/06/22);
insert into patient values(18,'anil','dk',08/07/22);
insert into patient values(19,'amulya','manipal',09/10/22);
insert into patient values(20,'ananda','manipal',10/10/22);
insert into politician values('modiji','gujrath',86,'bjp');
insert into politician values('amithsha','gujrath',76,'bjp');
insert into politician values('yadyurapp','karnataka',78,'bjp');
insert into politician values('bommaih','banglore',68,'bjp');
insert into politician values('kumarswami','mandya',56,'jdk');
insert into politician values('mankalv','bhatkal',66,'congress');
insert into politician values('shivanand','honnavar',56,'bjp');
insert into politician values('rahulgandi','mumbai',39,'congress');
insert into politician values('draupadi','gujrath',76,'bjp');
insert into politician values('shobha','ankola',46,'bjp');
insert into Grocery values(10,'haldiram',100,'snacks','100gm');
insert into Grocery values(12,'kroger',100,'snacks','100gm');
insert into Grocery values(13,'ralphs',100,'rice','10kg');
insert into Grocery values(14,'smiths',100,'snacks','100gm');
insert into Grocery values(15,'dmart',100,'snacks','100gm');
insert into Grocery values(16,'haldiram',100,'snacks','100gm');
insert into Grocery values(17,'mirinda',100,'juice','100ml');
insert into Grocery values(18,'haldiram',100,'snacks','100gm');
insert into Grocery values(19,'haldiram',100,'snacks','200gm');
insert into Grocery values(20,'haldiram',100,'snacks','20gm');
select *from historicalPlaces;
insert into historicalPlaces values('tajmahal',106,'mughal','up');
insert into historicalPlaces values('agraport',123,'dehli','delhi');
insert into historicalPlaces values('redport',106,'mughal','up');
insert into historicalPlaces values('qutubminar',108,'artdeco','bengal');
insert into historicalPlaces values('goldentemp',104,'mughal','gujrat');
insert into historicalPlaces values('ajanta',106,'gothic','kochhi');
insert into historicalPlaces values('khajuraho',120,'dummethod','haryan');
insert into historicalPlaces values('yamnarivr',150,'mughal','panjab');
insert into historicalPlaces values('jamamasjid',112,'traditional','karnataka');
insert into historicalPlaces values('palace',800,'mughal','mysore');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(804,'kalpana','chawl',10,'bengal');
insert into pilot values(805,'yamuna','chawdri',8,'kormangal');
insert into pilot values(807,'shruti','naik',11,'karnataka');
insert into pilot values(806,'meera','naik',12,'kormangal');
insert into pilot values(808,'mahesh','singh',13,'karnataka');
insert into pilot values(809,'krishnan','chawl',14,'hasan');
insert into pilot values(810,'maheshwar','bhola',15,'mumbhai');
insert into pilot values(811,'nagraj','yajn',16,'punjab');
insert into pilot values(813,'uday','pandey',18,'kormangal');
desc medicine;
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into pilot values(803,'mahendra','chawl',10,'kormangal');
insert into medicine values(002,01/02/22,01/02/24,280);
insert into medicine values(003,01/02/23,01/02/28,280);
insert into medicine values(004,01/03/22,01/12/24,280);
insert into medicine values(005,02/02/22,08/02/24,280);
insert into medicine values(006,11/02/20,01/02/24,280);
insert into medicine values(007,12/02/18,01/02/24,280);
insert into medicine values(008,22/02/23,01/02/24,280);
insert into medicine values(009,11/04/22,01/02/24,280);
insert into medicine values(001,20/02/22,01/02/24,280);
insert into medicine values(012,18/09/22,01/02/28,280);
USE sep1;
select * from artist

3).TCL
1. commit;
2. rollback;








